### ISSUE TITLE
Can't catch exception: InsufficientFunds

### ISSUE THREAD

**Issue by alfetopito** [laanwj/bitcoin-python#45]
Hello!

Well, from my understanding, I should be able to catch the InsufficientFunds exception, right?

``` python
>>> from bitcoinrpc.exceptions import InsufficientFunds
>>> try:
...     conn.sendtoaddress('n2ReFEassvxBRqcAvBhbe9muH9YGjMYk9s', 100)
... except InsufficientFunds:
...     pass
... 
Traceback (most recent call last):
  File "<input>", line 2, in <module>
  File "/home/vagrant/.pythonbrew/pythons/Python-2.7.3/lib/python2.7/site-packages/bitcoinrpc/connection.py", line 270, in sendtoaddress
    raise _wrap_exception(e.error)
WalletError: Insufficient funds
>>> 
```
No, can't do :(
Using bitcoin-python==0.3

Thanks.

**Comment by laanwj** [comment]
This repository is unmaintained (see https://github.com/laanwj/bitcoin-python#not-actively-maintained) so there is no one to handle issues. Closing this, sorry.
