### ISSUE TITLE
socket.error: [Errno 61] Connection refused

### ISSUE THREAD

**Issue by joohans** [laanwj/bitcoin-python#55]
Traceback (most recent call last):
  File "transaction.py", line 48, in <module>
    assert(conn.getinfo().testnet) # don't test on prodnet
  File "build/bdist.macosx-10.6-intel/egg/bitcoinrpc/connection.py", line 131, in getinfo
  File "build/bdist.macosx-10.6-intel/egg/bitcoinrpc/proxy.py", line 121, in __call__
  File "build/bdist.macosx-10.6-intel/egg/bitcoinrpc/proxy.py", line 72, in request
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 973, in request
    self._send_request(method, url, body, headers)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1007, in _send_request
    self.endheaders(body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 969, in endheaders
    self._send_output(message_body)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 829, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 791, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 772, in connect
    self.timeout, self.source_address)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 571, in create_connection
    raise err
socket.error: [Errno 61] Connection refused

**Comment by laanwj** [comment]
This repository is unmaintained (see https://github.com/laanwj/bitcoin-python#not-actively-maintained) so there is no one to handle issues. Closing this, sorry.
